spring:
  profiles:
    active: dev
---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/shopping
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
  h2:
    console:
      path: /h2
      enabled: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  port: 8080
---
#spring:
#  profiles: prod
#---
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/shopping
#    driver-class-name: org.h2.Driver
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    properties:
#      hibernate:
#        format_sql: true
#logging.level:
#  level: debug

# https://freehoon.tistory.com/125
# https://1-7171771.tistory.com/78
# https://blog.jiniworld.me/63
# TODO: AuthPage, Cart Page, Order Page, Order
