spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    # url: jdbc:h2:tcp://localhost/~/shopping
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
      # ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
server:
  port: 8080
---
spring:
  profiles: prod
